version: "3.9"

services:
  # postgres:
  #   image: postgres:latest
  #   container_name: deliveries
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./var/postgresql:/var/lib/postgresql/data:rw
  #     - ./cli:/cli
  #   env_file:
  #     - .env

  mongo:
    image: mongo
    container_name: rocketSocketMongo
    ports:
      - "27017:27017"

  api:
    build: .
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/usr/app
    command: yarn dev
